name: Linter

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: node:14.15.4-alpine3.12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
